language: node_js
node_js:
  - "8.9.3"

env:
  - FRAMEWORK=mocha CMD="mocha tests/chai.js tests/unit-js.js -R json" OUTFILE=mocha.json INSTALL="mocha chai unit.js" ANNOTATE_LOG=true

install:
  - npm install

script:
  - $CMD 2> build.log | tee $OUTFILE
  - cat build.log

after_failure:
  - if [ "$ANNOTATE_LOG" != false ]; then curl -s https://report.ci/upload.py | python - --include='*.json' --framework=mocha

after_script:
  - curl -s https://report.ci/upload.py | python - --include='*.json' --framework=mocha