language: node_js
node_js:
  - "10.16.0"

env:
  - FRAMEWORK=mocha CMD="mocha -R json" OUTFILE=mocha.json INSTALL="mocha chai unit.js" ANNOTATE_LOG=true

install:
  - npm install

script:
  - $CMD 2> build.log | tee $OUTFILE
  - cat build.log